### ISSUE TITLE
Same horizon for each study?

### ISSUE THREAD

**Issue by bcjaeger** [bcjaeger/melodem-apoe4-het#9]
Defining a treatment effect for the causal random survival forest requires specification of a horizon timepoint.

Should we use the same horizon for all datasets in our main analysis or use data-specific horizons?

**Comment by magali17** [comment]
We could consider estimating treatment effects at multiple fixed time intervals so that all cohorts produce estimates for the same time intervals. Some cohorts will have estimates for longer periods of time.

**Comment by bcjaeger** [comment]
I like this idea a lot! I will write a PR for this.
